### ISSUE TITLE
No records are shown when expected

### ISSUE THREAD

**Issue by dirkagterhuis** [Vacster/Domain-Process-Bindings-Explorer#16]
In some test org, I expected records to show up when I select the custom SObject, as there are Domain Process Binding custom metadata records configured for it. However, after selection, they didn't show up:

![image](https://user-images.githubusercontent.com/29105900/172603885-d537f333-939c-45b8-a803-67a2f26d2f05.png)

NB they also weren't there for other operations (insert/update).

**Comment by Vacster** [comment]
<img width="296" alt="image" src="https://user-images.githubusercontent.com/10774499/173670981-984ef03f-1f87-4f12-8022-9006495e8c83.png">

Seems like Salesforce is weird as shit and displays the `DeveloperName` of the related `EntityDefinition` (standard Salesforce lookup, nothing custom) without the suffix (e.g. `__c`)

**Comment by Vacster** [comment]
Proposed solution, use `QualifiedApiName` instead of `DeveloperName`: 
<img width="614" alt="image" src="https://user-images.githubusercontent.com/10774499/173671341-3404f833-487e-4985-aeed-7e2578c210a0.png">

Any thoughts on this @dirkagterhuis? I'm also using `QualifiedApiName` already on the LWCs because it works better when having multiple namespaces that would have SObject name collisions with just DeveloperName

**Comment by Vacster** [comment]
@dirkagterhuis would you please review proposed solution in PR #19

**Comment by Vacster** [comment]
Tried it on our Dev environment and seems to work but I'll double check on some more SObjects under namespaces to make sure it doesn't get confused before merging
